include_path = ../

mmap:
	gcc -I $(include_path) socket_wrapper_mmap_test.c -o mmap
send:
	gcc -I $(include_path) socket_wrapper_send_test.c -o send
send_connected:
	gcc -I $(include_path) socket_wrapper_send_test.c -o send_connected
