include_path = ../

mmap:
	gcc -I $(include_path) bzdg_mmap_test.c -o mmap
send:
	gcc -I $(include_path) bzdg_send_test.c -o send
send_connected:
	gcc -I $(include_path) bzdg_send_test.c -o send_connected
uapi_send:
	gcc -I $(include_path) bzdg_uapi_send_test.c -o uapi_send
